### PR TITLE
minor build fix in eval code

### PR DESCRIPTION
**Pull request by sayalikulkarni**

### CODE REVIEW

**Review by tzufgoogle — CHANGES_REQUESTED** [review]
I still get a build error: utils_test.py, line 18, in <module>: Can't find module 'cabby.evals'. [import-error]

**Comment by sayalikulkarni** [comment]
hmm am not sure whats going on... can you share the input file which gives this error?

i am able to run with both TSV and .pt files:
$ bazel run cabby/evals/eval_geo_model --   --input_file /mnt/hackney/data/cabby/evals/sample_predictions.tsv
INFO: Analyzed target //cabby/evals:eval_geo_model (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //cabby/evals:eval_geo_model up-to-date:
  bazel-bin/cabby/evals/eval_geo_model
INFO: Elapsed time: 0.287s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Starting evaluation.
Starting evaluation.
I1013 18:41:26.887788 139624536323904 utils.py:42] Starting evaluation.
Unexpected line format: [
]. Skipping
Unexpected line format: [
]. Skipping
W1013 18:41:26.890517 139624536323904 utils.py:61] Unexpected line format: [
]. Skipping
Metrics: 
Exact accuracy : [0.00]
mean error [159232.45], 
median error [31490.31]
max error [1871375.00]
AUC of error curve [0.64]
Metrics: 
Exact accuracy : [0.00]
mean error [159232.45], 
median error [31490.31]
max error [1871375.00]
AUC of error curve [0.64]
I1013 18:41:26.892266 139624536323904 utils.py:99] Metrics: 
Exact accuracy : [0.00]
mean error [159232.45], 
median error [31490.31]
max error [1871375.00]
AUC of error curve [0.64]

$ bazel run -- cabby/evals/eval_geo_model   --input_file /mnt/hackney/data/cabby/evals/metrics.pt   --preprocess_pytorch_output=true
INFO: Analyzed target //cabby/evals:eval_geo_model (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //cabby/evals:eval_geo_model up-to-date:
  bazel-bin/cabby/evals/eval_geo_model
INFO: Elapsed time: 0.223s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Preprocessing the pytorch output
I1013 18:42:00.038535 139852503635776 eval_geo_model.py:49] Preprocessing the pytorch output
I1013 18:42:00.040597 139852503635776 train.py:88] Results loaded from <== /mnt/hackney/data/cabby/evals/metrics.pt
Keys in state dictionary : [dict_keys(['train_loss_list', 'valid_loss_list', 'global_steps_list', 'valid_accuracy_list', 'true_points_list', 'pred_points_list'])]
I1013 18:42:00.040773 139852503635776 eval_geo_model.py:51] Keys in state dictionary : [dict_keys(['train_loss_list', 'valid_loss_list', 'global_steps_list', 'valid_accuracy_list', 'true_points_list', 'pred_points_list'])]
Intermediate raw data TSV is generated in : [/mnt/hackney/data/cabby/evals/metrics.pt.raw_data.tsv]
I1013 18:42:00.051446 139852503635776 eval_geo_model.py:61] Intermediate raw data TSV is generated in : [/mnt/hackney/data/cabby/evals/metrics.pt.raw_data.tsv]
Starting evaluation.
Starting evaluation.
I1013 18:42:00.052130 139852503635776 utils.py:42] Starting evaluation.
Metrics: 
Exact accuracy : [0.00]
mean error [1999.89], 
median error [1510.49]
max error [6962.15]
AUC of error curve [0.43]
Metrics: 
Exact accuracy : [0.00]
mean error [1999.89], 
median error [1510.49]
max error [6962.15]
AUC of error curve [0.43]
I1013 18:42:00.128051 139852503635776 utils.py:99] Metrics: 
Exact accuracy : [0.00]
mean error [1999.89], 
median error [1510.49]
max error [6962.15]
AUC of error curve [0.43]

**Comment by sayalikulkarni** [comment]
I think if you changed the output to make it a argmax over predictions, that may be the reason the format is different. Share the file and I will evaluate and fix this tonight.

**Comment by tzufgoogle** [comment]
/home/tzuf_google_com/tmp/output/dual/metrics.pt

**Review by tzufgoogle — APPROVED** [review]
LGTM

**Pull request merged**
